development:
  adapter: postgresql
  database: 11hao_dev
  host: localhost
  username: postgres
  password: 123456
test:
  adapter: postgresql
  database: 11hao_dev
  host: localhost
  username: postgres
  password: 123456